import type { Evidence } from "../../game/types";

export const recoveryFiles = [
  { id: "school.doc", title: "school.doc", source: "RECOVERED_FILE", originTime: "2007-08-12", integrity: "92%", body: ["南城二中摄影社", "暑期活动资料", "", "集合地点：旧体育馆侧门", "活动日期：8月17日", "集合时间：16:00", "", "注：网页通知由周然统一更新。"] },
  { id: "links.txt", title: "links.txt", source: "RECOVERED_FILE", originTime: "2007-08-09", integrity: "100%", body: ["linxia-home.net", "nc2ms.edu/club/photo/", "bluemoon-forum.net", "", "old home backup：/0817/backup/"] },
  { id: "music.txt", title: "music.txt", source: "RECOVERED_FILE", originTime: "2007-08-11", integrity: "71%", body: ["Window Rain", "Summer Platform", "Last Bus", "", "不要自动播放。"] },
  { id: "todo.txt", title: "todo.txt", source: "RECOVERED_FILE", originTime: "2007-08-16", integrity: "100%", body: ["相机充电", "把照片分一下", "还周然那本书", "问顾言网页空间", "打印报名表", "买空白光盘", "把上个月的图刻一份", "整理相册", "17号活动", "回来以后洗头", "", "照片先别删"] },
  { id: "photo_list.txt", title: "photo_list.txt", source: "RECOVERED_FILE", originTime: "2007-08-17 23:4x", integrity: "96%", body: ["0817 gym", "", "67 photos", "", "web：", "先选10-12张", "不要设备间那几张", "", "original：", "顾言那边有", "", "edit：", "亮度可能要调", "侧门那张太暗", "", "不要直接覆盖"] },
  { id: "0817.txt", title: "0817.txt", source: "RECOVERED_FILE", originTime: "2007-08-17 23:52", integrity: "100%", originalName: "note3.txt", body: ["17号。", "", "下午去体育馆。", "", "一开始没什么。", "陈海还是一直拍人，周然一直催时间。", "顾言比我们早到。", "", "设备间那些图不发可以。", "但为什么一定要删。", "", "周然说意思一样。", "", "我现在最烦这句话。", "", "顾言那边有原来的。", "", "明天再说。"] },
  { id: "diary.txt", title: "diary.txt", source: "RECOVERED_FILE", originTime: "2007-08", integrity: "84%", body: ["[2007.07.28] 下雨", "[2007.08.03] 原图", "[2007.08.09] 公交车最后一排", "[2007.08.12] 把页面改回去了", "", "[drafts]", "draft_0816", "draft_0817", "draft_0818", "", "Some entries unavailable."] },
  { id: "draft_0816.txt", title: "drafts/draft_0816.txt", source: "RECOVERED_FILE", originTime: "2007-08-16 23:08", integrity: "93%", body: ["明天去旧体育馆。", "", "周然说不要临时改。", "可是网页日期本来就不是我改的。", "", "先把相机充上。"] },
  { id: "draft_0817.txt", title: "drafts/draft_0817.txt", source: "RECOVERED_FILE", originTime: "2007-08-17 22:36", integrity: "67%", body: ["顾言说原来的还在。", "", "设备间那几张不发。", "但是不要删。", "", "这两件事不是一个意思。"] },
  { id: "draft_0818.txt", title: "drafts/draft_0818.txt", source: "RECOVERED_FILE", originTime: "2007-08-18 00:31", integrity: "38%", body: ["17号我没有出门。", "", "...", "", "写成这样以后看起来居然也挺像真的。", "", "...", "", "算了。"] },
  { id: "unsent.txt", title: "unsent.txt", source: "RECOVERED_FILE", originTime: "2007-08-18 01:4x", integrity: "84%", body: ["如果以后有人看到这些东西，", "大概又会觉得我当时一定在想什么特别严重的事。", "", "其实没有。", "", "我只是很烦。", "", "有些东西删了以后别人会自己补一个原因。", "不删又会有人觉得留下来的就是答案。", "", "先存着。", "不发。"] },
  { id: "summary_0817.txt", title: "summary_0817.txt", source: "GENERATED", originTime: "Generated by Recovery Index", integrity: "N/A", body: ["Generated Summary", "", "林夏于8月17日下午参加旧体育馆摄影活动，与周然发生争执后离开。", "该摘要由 Recovery Index 根据多个来源生成。"] },
  { id: "note1.txt", title: "temp/note1.txt", source: "RECOVERED_FILE", originTime: "2007-08", integrity: "100%", body: ["买电池"] },
];

export const recoveryThreads = {
  妈妈: ["妈：晚上回来吃饭吗", "林夏：不知道", "妈：冰箱有菜", "林夏：嗯", "妈：别又只吃面", "林夏：知道了"],
  周然: ["周然：明天别又临时改。", "林夏：我没有改过。", "周然：我是说计划。", "林夏：你每次都这样。", "周然：又怎么了。", "[cache incomplete]"],
  顾言: ["林夏：原来的还在？", "顾言：在。", "林夏：别删。", "顾言：嗯。", "", "顾言：网页空间又快满了。"],
  摄影社群: ["周然：17号四点，旧体育馆侧门。", "陈海：我带电池。", "徐晓：我可能晚一点。", "林夏：知道了。"],
  leaf: ["leaf：你最近怎么老说删东西。", "Summer17：因为硬盘快满了。"],
  night_train: ["night_train：你主页那个旧地址还能开吗？", "Summer17：缓存里可以。", "night_train：那就别急着关。", "Summer17：不是关不关的问题。"],
  Unknown: ["这里看起来更像她，对吗？", "", "Source: Unresolved / Current Recovery Session"],
} as const;

export const recoveryThreadSources: Record<keyof typeof recoveryThreads, { source: string; origin: string; completeness: string; mappedView: string }> = {
  妈妈: { source: "MESSENGER_CACHE", origin: "backup_20070823", completeness: "COMPLETE", mappedView: "Messenger" },
  周然: { source: "MESSENGER_CACHE", origin: "backup_20070823", completeness: "PARTIAL", mappedView: "Messenger" },
  顾言: { source: "MESSENGER_CACHE + EMAIL_CACHE", origin: "backup_20070823", completeness: "LINKED", mappedView: "Messenger" },
  摄影社群: { source: "GROUP_CACHE", origin: "backup_20070823", completeness: "COMPLETE", mappedView: "Messenger" },
  leaf: { source: "FORUM_PRIVATE_MESSAGE", origin: "BlueMoon Archive", completeness: "PARTIAL", mappedView: "Messenger" },
  night_train: { source: "FORUM_PRIVATE_MESSAGE", origin: "BlueMoon Archive", completeness: "PARTIAL", mappedView: "Messenger" },
  Unknown: { source: "CURRENT_SESSION / UNRESOLVED", origin: "Current Recovery Session", completeness: "DYNAMIC", mappedView: "Messenger" },
};

export const linkedRecoveryEmail = {
  id: "EMAIL:GUYAN:2241",
  time: "2007-08-17 22:41",
  from: "林夏",
  to: "顾言",
  source: "EMAIL_CACHE",
  subject: "照片",
  body: ["照片先别删。", "明天我会处理。"],
};

export const personalCalendarEvents = [
  ["08/03", "整理摄影社原图"],
  ["08/08", "更新个人主页"],
  ["08/12", "把旧主页改回去"],
  ["08/14 16:00", "摄影社讨论"],
  ["08/17 16:00", "旧体育馆活动"],
  ["08/18", "无个人事件"],
  ["08/27", "返校"],
] as const;

export const recoveredCalendarEvents = [
  ["2015-09-04", "Source package catalogued", "ARCHIVE_EVENT"],
  ["2016-03-17 03:17", "Environment Build", "RECOVERY_EVENT"],
  ["2016-03-17 03:17", "Calendar objects mapped", "RECOVERY_EVENT"],
] as const;

export const recoveryBrowserHistory = [
  ["2007-08-17 20:31", "BlueMoon / 如果一个人突然不再存在", "/forum/thread/1847"],
  ["2007-08-17 19:14", "林夏の小窝 / 0817", "/site/2007/linxia/0817/"],
  ["2007-08-15 18:02", "摄影社暑期活动通知", "/archive/20070815/nc2ms.edu/photo-event"],
  ["2007-08-12 23:46", "BlueMoon / 主页到底要不要关", "/forum/thread/1711"],
] as const;

export const chapter04EvidenceRegistry: Record<string, Evidence> = {
  E041_recovery_environment_build: { id: "E041_recovery_environment_build", title: "Recovery Environment Build：2016-03-17", sourceType: "SYSTEM", summary: "Recovery Information 显示 2007-Legacy 只是 Display Profile，环境由 2016 构建。", supports: ["knows_desktop_is_recovery_shell"] },
  E042_messenger_source_mapping: { id: "E042_messenger_source_mapping", title: "Messenger Source Mapping", sourceType: "SYSTEM", summary: "BlueMoon 私信被映射进统一 Messenger 联系人界面。", supports: ["knows_messenger_is_aggregated_view"] },
  E043_calendar_observer_events: { id: "E043_calendar_observer_events", title: "Calendar：Current Observer Session", sourceType: "SESSION", summary: "Recovery Calendar 同时展示历史事件与当前玩家在 ROOM 中的操作。", supports: ["knows_calendar_contains_observer_data"] },
  E044_environment_manifest: { id: "E044_environment_manifest", title: "environment.manifest", sourceType: "SYSTEM", summary: "manifest 记录 environment_id、2007_LEGACY display profile 与 continuity merge policy。", supports: ["knows_environment_manifest"] },
  E045_recovery_log: { id: "E045_recovery_log", title: "recovery.log：Building user shell", sourceType: "SYSTEM", summary: "2016 恢复日志显示系统映射来源、归一化时间并构建用户 Shell。", supports: ["knows_ui_continuity_is_constructed"] },
  E046_persona_memory_graph: { id: "E046_persona_memory_graph", title: "Persona Memory Graph：ERROR", sourceType: "SYSTEM", summary: "MEMORY ERROR 指向人物记忆图连续性失败，而不是硬件内存故障。", supports: ["knows_memory_error_is_persona_graph"] },
  E047_raw_vs_shell: { id: "E047_raw_vs_shell", title: "Raw Directory 与 Recovery Shell 不一致", sourceType: "RECOVERED", summary: "原始目录是碎片化文件夹，Recovery Shell 将其组织成 Documents、Photos、Messages 与 Calendar。", supports: ["knows_raw_directory_differs_from_shell", "knows_ui_continuity_is_constructed"] },
  E048_unknown_current_session_source: { id: "E048_unknown_current_session_source", title: "Unknown：Current Recovery Session", sourceType: "SESSION", summary: "Unknown 没有 2007 来源，被标记为当前 Recovery Session 中的未解析对象。", supports: ["knows_unknown_not_original_contact"] },
  E050_draft_0818_self_report: { id: "E050_draft_0818_self_report", title: "draft_0818：17号我没有出门", sourceType: "RECOVERED", summary: "林夏写下了一段与其他来源冲突的自我叙述；文件本身是真实恢复对象，但内容不是客观事实。", supports: ["knows_self_report_can_conflict_with_sources"] },
  E051_mail_unsent_0203: { id: "E051_mail_unsent_0203", title: "mail_unsent.eml：02:03 Fragment", sourceType: "RECOVERED", summary: "未发送邮件主动否定“最后的话”，只表达想暂时离开一天，不能解释为遗书。", supports: ["knows_unsent_mail_is_not_farewell"] },
  E052_raw_name_mapping: { id: "E052_raw_name_mapping", title: "Raw Name Mapping", sourceType: "SYSTEM", summary: "Recovery Shell 的可读文件名和目录来自系统映射，原始目录名称更混乱。", supports: ["knows_recovery_names_are_mapped"] },
  E053_generated_summary_example: { id: "E053_generated_summary_example", title: "Generated Summary Example", sourceType: "GENERATED", summary: "summary_0817 是 Recovery Index 生成摘要，没有对应的原始文件证据。", supports: ["knows_generated_summary_is_not_source"] },
  E054_relevance_sort_policy: { id: "E054_relevance_sort_policy", title: "Recovery Relevance Sort Policy", sourceType: "SYSTEM", summary: "Documents 默认按 Recovery Index 的相关度排序；排列顺序本身是系统叙述。", supports: ["knows_sort_order_is_interpretation"] },
  E060_zhou_cache_conflict: { id: "E060_zhou_cache_conflict", title: "周然消息缓存：改动争议", sourceType: "RECOVERED", summary: "8月16日的缓存显示林夏否认自己改过，周然随后将对象改称为“计划”。", supports: ["knows_messenger_conflict_is_ambiguous"] },
  E061_guyan_original_confirmation: { id: "E061_guyan_original_confirmation", title: "顾言消息：原来的还在", sourceType: "RECOVERED", summary: "顾言确认原始对象仍在，并在关联邮件中收到“照片先别删”的要求。", supports: ["knows_guyan_has_originals"] },
  E062_group_event_message: { id: "E062_group_event_message", title: "摄影社群：8月17日四点", sourceType: "RECOVERED", summary: "群聊保存了旧体育馆侧门与16:00集合时间，顾言会更早到。", supports: ["knows_group_cache_confirms_event"] },
  E063_forum_pm_mapping: { id: "E063_forum_pm_mapping", title: "Forum PM mapped into Messenger", sourceType: "SYSTEM", summary: "leaf 与 night_train 线程来自论坛私信，而非即时通讯缓存。", supports: ["knows_messenger_is_aggregated_view"] },
  E064_linked_email_cache: { id: "E064_linked_email_cache", title: "Linked Email：照片先别删", sourceType: "RECOVERED", summary: "22:41 的 EMAIL_CACHE 被映射到顾言联系人线程，但保留独立来源。", supports: ["knows_linked_email_is_distinct_source"] },
  E065_messenger_source_help: { id: "E065_messenger_source_help", title: "Recovery Messenger Source Mapping", sourceType: "SYSTEM", summary: "统一联系人界面可以聚合即时消息、群聊、论坛私信、邮件与当前 Session。", supports: ["knows_messenger_is_aggregated_view"] },
  E070_personal_calendar: { id: "E070_personal_calendar", title: "Personal Calendar：2007-08", sourceType: "RECOVERED", summary: "个人日历保存8月3日至27日的事件；8月18日没有个人事件。", supports: ["knows_calendar_personal_layer"] },
  E071_recovery_calendar_layer: { id: "E071_recovery_calendar_layer", title: "Recovered Events Layer", sourceType: "SYSTEM", summary: "恢复日历额外映射2015来源包和2016环境构建事件。", supports: ["knows_calendar_recovery_layer"] },
  E072_session_calendar_layer: { id: "E072_session_calendar_layer", title: "Current Session Calendar", sourceType: "SESSION", summary: "Session 日历与 session.log 读取同一份玩家操作 Event Store。", supports: ["knows_calendar_session_layer"] },
  E073_recovery_anchor_0317: { id: "E073_recovery_anchor_0317", title: "03:17 Recovery Scheduler Anchor", sourceType: "SYSTEM", summary: "03:17 是2016恢复任务的调度锚点，而非2007个人事件。", supports: ["knows_0317_is_recovery_anchor"] },
  E074_calendar_empty_0818: { id: "E074_calendar_empty_0818", title: "2007-08-18：No Personal Event", sourceType: "RECOVERED", summary: "日历的空白只表示无恢复到的个人事件，不证明当天现实活动。", supports: ["knows_calendar_absence_is_not_fact"] },
};
