import type { Evidence, PhotoEntry } from "../../game/types";

export const archiveRecent = [
  {
    title: "南城旧城区个人主页索引",
    meta: "最后快照：2008-02-14",
    path: "/search?q=2007%20个人主页",
  },
  {
    title: "南城市立第二中学校园网（旧版）",
    meta: "最后快照：2008-06-01",
    path: "/site/2003/nc2ms",
  },
  {
    title: "林夏の小窝",
    meta: "最后快照：2008-02-14",
    path: "/site/2007/linxia",
  },
  {
    title: "BlueMoon Community",
    meta: "状态：部分损坏",
    path: "/search?q=BlueMoon",
  },
];

export const searchResults = [
  {
    title: "林夏の小窝",
    url: "http://linxia-home.net/",
    captured: "Captured: 2008-02-14",
    snippet: "☆ Welcome to Linxia's Home Page ☆ About / Diary / Photo / Guestbook / Links",
    path: "/site/2007/linxia",
  },
  {
    title: "南城二中摄影社活动记录",
    url: "nc2ms.edu/club/photo/",
    captured: "Captured: 2007-08-19",
    snippet: "影像兴趣小组 / 摄影社 - 暑期旧体育馆采风活动",
    path: "/site/2003/nc2ms/clubs/photo",
  },
  {
    title: "BlueMoon - 用户资料：Linxia",
    url: "bluemoon.local/u/linxia",
    captured: "Captured: 2009-01-17",
    snippet: "Status: Partial. Forum archive unavailable in this build.",
    path: "/missing/bluemoon/linxia",
  },
  {
    title: "留言板缓存 - Ran's Place",
    url: "ran-place.net/guestbook/cache",
    captured: "Captured: 2007-10-03",
    snippet: "Status: Missing Resources",
    path: "/missing/ran-place",
  },
  {
    title: "林夏个人主页 - 旧快照",
    url: "linxia-home.net/archive/20070812",
    captured: "Captured: 2007-08-12",
    snippet: "Last Updated: 2007.08.12",
    path: "/site/2007/linxia",
  },
];

export const archiveExtendedSearchResults = [
  {
    title: "林夏 Diary 缓存索引",
    url: "linxia-home.net/diary/",
    captured: "Captured: 2008-02-14",
    snippet: "把页面改回去了 / 公交车最后一排 / 原图。共 29 条可读日记对象。",
    path: "/site/2007/linxia/diary",
  },
  {
    title: "林夏 Photo Album 目录",
    url: "linxia-home.net/photo/",
    captured: "Captured: 2008-02-14",
    snippet: "02 空教室、05 公交站、08 旧城区招牌、11 周然背影、13 顾言在弄电脑、17 旧体育馆侧门。",
    path: "/site/2007/linxia/photo",
  },
  {
    title: "Guestbook 2007 / 08",
    url: "linxia-home.net/guestbook/",
    captured: "Captured: 2007-08-12",
    snippet: "页面字体、照片标题、网页目录和 17 号活动的留言仍可从缓存中读取。",
    path: "/site/2007/linxia/guestbook",
  },
  {
    title: "南城市立第二中学校园网",
    url: "nc2ms.edu/",
    captured: "Captured: 2008-06-01",
    snippet: "校园新闻、摄影社、旧公告和暑期采风活动页面。",
    path: "/site/2003/nc2ms",
  },
  {
    title: "南城二中摄影社 / 影像兴趣小组",
    url: "nc2ms.edu/club/photo/",
    captured: "Captured: 2007-08-19",
    snippet: "林夏、周然、顾言、陈海、徐晓。原始文件在社团电脑中另有复制。",
    path: "/site/2003/nc2ms/clubs/photo",
  },
  {
    title: "摄影社暑期活动公告：原始快照",
    url: "archive/20070815/nc2ms.edu/photo-event",
    captured: "ORIGINAL / 2007-08-15",
    snippet: "集合时间：下午 4 时。活动日期：2007 年 8 月 17 日。",
    path: "/archive/20070815/nc2ms.edu/photo-event",
  },
  {
    title: "摄影社暑期活动公告：后续快照",
    url: "archive/20070819/nc2ms.edu/photo-event",
    captured: "ALTERED / 2007-08-19",
    snippet: "同一公告的活动日期变为 2007 年 8 月 18 日，发布时间晚于活动本身。",
    path: "/archive/20070819/nc2ms.edu/photo-event",
  },
  {
    title: "Photo17 / DSC0417.JPG Forensics",
    url: "room.local/photo/forensics/DSC0417.JPG",
    captured: "Source chain required",
    snippet: "网页变体、社团原始副本、2007 恢复副本和后续重建对象分开保存。",
    path: "/photo/forensics/DSC0417",
  },
  {
    title: "BlueMoon Community Archive",
    url: "bluemoon-forum.net/",
    captured: "Partial / 2007-08-17",
    snippet: "论坛首页、板块索引、Summer17 用户和缓存主题。",
    path: "/archive/20070817/bluemoon-forum.net/",
  },
  {
    title: "ROOM Recovery System",
    url: "room.local/recovery/boot",
    captured: "Recovered environment / 2016",
    snippet: "Environment Build 2016.03。来源包：backup_20070823。Memory：ERROR。",
    path: "/recovery/boot",
  },
  {
    title: "Recovery Shell / SUBJECT_04",
    url: "room.local/recovery/login",
    captured: "Read-only environment",
    snippet: "显示配置为 2007-Legacy，Recovery Shell 不是林夏现实电脑的证明。",
    path: "/recovery/login",
  },
  {
    title: "ROOM Continuity Service",
    url: "room.local/service/continuity",
    captured: "Current archive service",
    snippet: "Subject 04、Subject 404、Unknown 和 Current Observer 的连续性接口。",
    path: "/service/continuity",
  },
  {
    title: "UNRESOLVED_PERSONA / Unknown",
    url: "room.local/object/UNRESOLVED_PERSONA",
    captured: "Mixed source interface",
    snippet: "承载跨来源 Persona 输出，稳定身份：NONE。",
    path: "/object/UNRESOLVED_PERSONA",
  },
];

export const diaryEntries = [
  {
    id: "diary_20070812",
    date: "2007.08.12",
    title: "把页面改回去了",
    body: [
      "前几天有人说上面的标题太小，顺手帮我改了一下。",
      "今天又改回来了。",
      "不是不好看，就是看着很奇怪。",
      "明明还是同一句话，换了字体、换了位置以后就感觉不是原来那个东西了。",
      "可能只有我会在意这种事。",
      "算了，反正已经改回来了 XD",
    ],
  },
  {
    id: "diary_20070809",
    date: "2007.08.09",
    title: "公交车最后一排",
    body: [
      "今天回来的时候坐最后一排。",
      "前面有个人一路都在睡，司机刹车的时候差点从椅子上滑下去。",
      "窗外经过老城区那边，很多店都关了。有一家照相馆的牌子还在，玻璃里面什么都没有。",
      "本来想拍，后来车开太快。",
      "下次吧。",
      "还有，17路今天又晚点。我已经不想吐槽它了。",
    ],
  },
  {
    id: "diary_20070803",
    date: "2007.08.03",
    title: "原图",
    body: [
      "今天整理上学期的图，发现有一张被改过亮度以后直接盖掉了。",
      "我知道其实也没什么区别。甚至改过以后比较好看。",
      "但还是很不爽。",
      "后来在旧文件夹里找到原来的了。",
      "以后还是分开存吧。",
      "original / edit / web",
      "这样比较省事。",
      "顾言说早就应该这样。",
      "好吧，他赢了。",
    ],
  },
  {
    id: "diary_20070728",
    date: "2007.07.28",
    title: "下雨",
    body: [
      "下午突然下雨。",
      "我没带伞。",
      "周然站在教学楼门口笑了我大概五分钟，然后说他只有一把。",
      "我说那你笑完了没有。",
      "他说没有。",
      "最后还是一起走到车站。",
      "路上水特别大，我鞋已经完全没救。",
      "到车站以后才发现顾言还在机房。",
      "晚上他发消息说网页有三张图路径写错了。",
      "我问他为什么下午不走。",
      "他说因为网页坏了。",
      "很好。",
      "每个人都有自己的优先级。",
    ],
  },
  {
    id: "diary_20070714",
    date: "2007.07.14",
    title: "好像什么都没做",
    body: [
      "今天认真回想了一下，发现暑假开始到现在好像什么都没做。",
      "想整理照片。没整理。",
      "想把首页换掉。没换。",
      "想出去拍点东西。太热。",
      "周然说高三之前应该“做一点有意义的事”。",
      "我问什么算有意义。",
      "他说至少别每天坐在电脑前。",
      "然后他自己下午打了三个小时游戏。",
      "很有意义。",
    ],
  },
];

export const ordinaryDiaryEntries = [
  { id: "diary_ordinary_001", date: "ordinary-001", title: "网页又打不开", body: ["我妈说桌面太乱，让我整理。我把东西全塞进另一个文件夹。写完发现更没意思。"] },
  { id: "diary_ordinary_002", date: "ordinary-002", title: "公交车特别慢", body: ["旧城区那家照相馆门一直关着，橱窗里还有去年的广告。算了。"] },
  { id: "diary_ordinary_003", date: "ordinary-003", title: "备份", body: ["把旧主页备份了一份，怕自己哪天又改坏。其实也没什么。"] },
  { id: "diary_ordinary_004", date: "ordinary-004", title: "相册顺序", body: ["回家路上风很大。相册顺序排了半天，最后发现其实没人会认真看顺序。反正先这样。"] },
  { id: "diary_ordinary_005", date: "ordinary-005", title: "桌面太乱", body: ["作业还没写。我把东西全塞进另一个文件夹。以后再看。"] },
  { id: "diary_ordinary_006", date: "ordinary-006", title: "没用的照片", body: ["今天拍了很多没用的照片。把旧主页备份了一份，怕自己哪天又改坏。写完发现更没意思。"] },
  { id: "diary_ordinary_007", date: "ordinary-007", title: "徐晓没来", body: ["突然想整理文件。徐晓今天没来，说家里有事。其实也没什么。"] },
  { id: "diary_ordinary_008", date: "ordinary-008", title: "借电池", body: ["学校机房很热。陈海又借电池没还。明天再说。"] },
  { id: "diary_ordinary_009", date: "ordinary-009", title: "网站维护", body: ["网页又打不开。陈海又借电池没还。反正先这样。"] },
  { id: "diary_ordinary_010", date: "ordinary-010", title: "留下来", body: ["下午很困。有些东西留着只是因为懒得删，也不代表多重要。写完发现更没意思。"] },
  { id: "diary_ordinary_011", date: "ordinary-011", title: "没什么", body: ["突然想整理文件。徐晓今天没来，说家里有事。明天再说。"] },
  { id: "diary_ordinary_012", date: "ordinary-012", title: "新建文件夹(2)", body: ["作业还没写。新建文件夹(2)到底是什么，我已经完全忘了。以后再看。"] },
  { id: "diary_ordinary_013", date: "ordinary-013", title: "背影", body: ["今天拍了很多没用的照片。周然说我拍人总拍背影，我觉得背影比较安静。先留着。"] },
  { id: "diary_ordinary_014", date: "ordinary-014", title: "照相馆", body: ["今天没什么。旧城区那家照相馆门一直关着，橱窗里还有去年的广告。不改了。"] },
  { id: "diary_ordinary_015", date: "ordinary-015", title: "乱码歌曲", body: ["作业还没写。下载了一首歌，名字全是乱码。不改了。"] },
  { id: "diary_ordinary_016", date: "ordinary-016", title: "风很大", body: ["回家路上风很大。新建文件夹(2)到底是什么，我已经完全忘了。明天再说。"] },
  { id: "diary_ordinary_017", date: "ordinary-017", title: "没用的照片", body: ["今天拍了很多没用的照片。新建文件夹(2)到底是什么，我已经完全忘了。以后再看。"] },
  { id: "diary_ordinary_018", date: "ordinary-018", title: "不太想说话", body: ["晚上不太想说话。徐晓今天没来，说家里有事。其实也没什么。"] },
  { id: "diary_ordinary_019", date: "ordinary-019", title: "顾言的代码", body: ["相机又没电。顾言发了一串代码过来，说让我自己改，我没看懂。算了。"] },
  { id: "diary_ordinary_020", date: "ordinary-020", title: "不太想说话", body: ["晚上不太想说话。徐晓今天没来，说家里有事。明天再说。"] },
  { id: "diary_ordinary_021", date: "ordinary-021", title: "整理桌面", body: ["今天拍了很多没用的照片。我妈说桌面太乱，让我整理。我把东西全塞进另一个文件夹。算了。"] },
  { id: "diary_ordinary_022", date: "ordinary-022", title: "机房很热", body: ["学校机房很热。顾言发了一串代码过来，说让我自己改，我没看懂。先留着。"] },
  { id: "diary_ordinary_023", date: "ordinary-023", title: "相册顺序", body: ["今天拍了很多没用的照片。相册顺序排了半天，最后发现其实没人会认真看顺序。反正先这样。"] },
  { id: "diary_ordinary_024", date: "ordinary-024", title: "下午很困", body: ["下午很困。顾言发了一串代码过来，说让我自己改，我没看懂。先留着。"] },
];

export const guestbookEntries = [
  {
    no: "#183",
    author: "小叶",
    date: "2007/08/10",
    text: "首页背景终于不闪了……",
    reply: "之前那个我自己看久了都头痛 XD",
  },
  {
    no: "#180",
    author: "Ran",
    date: "2007/08/07",
    text: "你那个照片标题能不能写清楚点",
    reply: "不能",
  },
  {
    no: "#176",
    author: "GY",
    date: "2007/08/03",
    text: "web目录少一张图",
    reply: "晚点补",
  },
  {
    no: "#172",
    author: "Ran",
    date: "2007/08/11",
    text: "17号那个活动别忘了。下午。",
    reply: "知道了",
  },
  {
    no: "#169",
    author: "system",
    date: "2007/08/12",
    text: "[该留言已被删除]",
    reply: "",
  },
];

export const photoEntries: PhotoEntry[] = [
  {
    id: "02",
    title: "空教室",
    caption: "下午四点的教室。窗帘老是挡镜头。",
    assetId: "linxia_photo_02",
  },
  {
    id: "05",
    title: "公交站",
    caption: "又晚点。",
    assetId: "linxia_photo_05",
  },
  {
    id: "08",
    title: "旧城区招牌",
    caption: "这家店到底还开不开。",
    assetId: "linxia_photo_08",
  },
  {
    id: "11",
    title: "周然背影",
    caption: "某人说一定要拍“活动感”。",
    assetId: "linxia_photo_11",
  },
  {
    id: "13",
    title: "顾言在弄电脑",
    caption: "网站又坏了。",
    assetId: "linxia_photo_13",
  },
  {
    id: "17",
    title: "旧体育馆侧门",
    caption: "门锁坏了三年好像也没人修。",
    assetId: "photo17_web_v0",
    routePath: "/site/2007/linxia/photo/17",
  },
];

export const evidenceRegistry: Record<string, Evidence> = {
  E001_school_original_notice: {
    id: "E001_school_original_notice",
    title: "学校原始公告：活动日期为17号",
    sourceType: "ORIGINAL",
    summary: "2007-08-15 快照显示摄影社活动日期为 2007年8月17日。",
    supports: ["knows_event_date_changed"],
  },
  E002_school_modified_notice: {
    id: "E002_school_modified_notice",
    title: "学校后续公告：活动日期被改为18号",
    sourceType: "ALTERED",
    summary: "2007-08-19 快照显示同一活动日期变为 2007年8月18日。",
    supports: ["knows_event_date_changed"],
  },
  E014_private_0817: {
    id: "E014_private_0817",
    title: "private.html：林夏的未公开记录",
    sourceType: "ARCHIVED",
    summary: "林夏写下“今天活动是17号”，并提到周然准备把对外日期改成18号、要求删除照片，以及顾言保存原图。",
    supports: [
      "knows_linxia_attended_event",
      "knows_zhouran_requested_delete",
      "knows_guyan_has_originals",
    ],
  },
};
